on:
  push:
    branches:
      - main
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-version: latest
        ghc-version: latest
    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: stack-cache
    - name: Build site builder
      run: |
        stack build --system-ghc
    - name: Build site
      run: |
        stack exec site  rebuild
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: _site/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
